import { Department } from "./department";
import { Stage } from "./stage";
import { ProjectGroup } from "./project-group";
import { Client } from "./client";

export interface Project {
	id?: number;
	name: string;
	description: string;
	createdAt?: string;
	stages: Stage[];
	department?: Department;
	emails?: string[];
	phoneNumbers?: string[];
	group?: ProjectGroup;
	hasOverdueTasks?: boolean;
	isArchived?: boolean;
	collaborators?: { id: number; name: string; email: string; department_id?: number; role?: string }[];
	mattermostChannelId?: string;
	clientId?: number;
	estimatedHours?: number;
	status?: 'active' | 'on-hold' | 'completed' | 'cancelled' | 'suggested' | 'blocked';
	client?: Client;
	poNumber?: string;
	poDocument?: string;
	poDocumentUrl?: string;
	isLockedByPo?: boolean;
	isBlocked?: boolean;
	deadline?: string;
	invoiceNumber?: string;
	invoiceDocument?: string;
	invoiceDocumentUrl?: string;
	projectCode?: string;
	estimateId?: number;
	gracePeriodExpiresAt?: string;
	gracePeriodNotes?: string;
	gracePeriodApprovedBy?: string;
	provisionalPoNumber?: string;
	provisionalPoExpiresAt?: string;
	isPhysicalInvoice?: boolean;
	courierTrackingNumber?: string;
	courierDeliveryStatus?: string;
	currency?: string;
	campaign_report_document?: string;
	campaign_report_status?: 'pending' | 'approved';
	campaign_report_approved_by?: number;
	campaign_report_approved_at?: string;
	campaign_report_document_url?: string;
	totalRevenue?: number;
	totalCost?: number;
	actualProfit?: number;
	profitMarginPercentage?: number;
}
